// apps/frontend/app/admin/problem/create/page.tsx
'use client'

import CheckboxSelect from '@/components/CheckboxSelect'
import OptionSelect from '@/components/OptionSelect'
import TagsSelect from '@/components/TagsSelect'
import TextEditor from '@/components/TextEditor'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import {
  Popover,
  PopoverContent,
  PopoverTrigger
} from '@/components/ui/popover'
import { ScrollArea, ScrollBar } from '@/components/ui/scroll-area'
import { Switch } from '@/components/ui/switch'
import { Textarea } from '@/components/ui/textarea'
import { CREATE_PROBLEM } from '@/graphql/problem/mutations'
import { GET_TAGS } from '@/graphql/problem/queries'
import { languages, levels } from '@/lib/constants'
import { cn } from '@/lib/utils'
import { useMutation, useQuery } from '@apollo/client'
import { Level, type CreateProblemInput, Template } from '@generated/graphql'
import { zodResolver } from '@hookform/resolvers/zod'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { useEffect, useState } from 'react'
import { useForm, Controller } from 'react-hook-form'
import { FaEye, FaEyeSlash } from 'react-icons/fa'
import { FaAngleLeft } from 'react-icons/fa6'
import { IoMdCheckmarkCircleOutline } from 'react-icons/io'
import { MdHelpOutline } from 'react-icons/md'
import { PiWarningBold } from 'react-icons/pi'
import { toast } from 'sonner'
import { z } from 'zod'
import ExampleTextarea from '../_components/ExampleTextarea'
import Label from '../_components/Label'
import { inputStyle } from '../utils'

const schema = z.object({
  title: z.string().min(1).max(200),
  isVisible: z.boolean(),
  difficulty: z.enum(levels),
  languages: z.array(z.enum(languages)),
  tagIds: z.array(z.number()),
  description: z.string().min(1),
  inputDescription: z.string().min(1),
  outputDescription: z.string().min(1),
  samples: z
    .array(
      z.object({
        input: z.string().min(1),
        output: z.string().min(1)
      })
    )
    .min(1),
  testcases: z
    .array(
      z.object({
        input: z.string().min(1),
        output: z.string().min(1)
      })
    )
    .min(1),
  timeLimit: z.number().min(0),
  memoryLimit: z.number().min(0),
  hint: z.string().optional(),
  source: z.string().optional(),
  template: z
    .array(
      z
        .object({
          language: z.enum([
            'C',
            'Cpp',
            'Golang',
            'Java',
            'Python2',
            'Python3'
          ]),
          code: z.array(
            z.object({
              id: z.number(),
              text: z.string(),
              locked: z.boolean()
            })
          )
        })
        .optional()
    )
    .optional()
})

export default function Page() {
  const { data: tagsData } = useQuery(GET_TAGS)
  const tags =
    tagsData?.getTags.map(({ id, name }) => ({ id: Number(id), name })) ?? []
  const [showHint, setShowHint] = useState(false)
  const [showSource, setShowSource] = useState(false)
  const [isCreating, setIsCreating] = useState(false)

  const router = useRouter()

  const {
    handleSubmit,
    control,
    register,
    getValues,
    watch,
    setValue,
    formState: { errors }
  } = useForm<CreateProblemInput>({
    resolver: zodResolver(schema),
    defaultValues: {
      difficulty: Level.Level1,
      tagIds: [],
      samples: [{ input: '', output: '' }],
      testcases: [{ input: '', output: '' }],
      hint: '',
      source: '',
      template: [],
      isVisible: true
    }
  })

  const watchedSamples = watch('samples')
  const watchedTestcases = watch('testcases')
  const watchedLanguages = watch('languages')

  useEffect(() => {
    if (watchedLanguages) {
      let templates: Template[] = [] // temp array to store templates
      const savedTemplates = getValues('template') // templates saved in form
      watchedLanguages.map((language) => {
        const temp = savedTemplates!.filter(
          (template) => template.language === language
        )
        if (temp.length !== 0) {
          templates.push(temp[0])
        } else {
          // push dummy template to array
          templates.push({
            language,
            code: [
              {
                id: -1,
                text: '',
                locked: false
              }
            ]
          })
        }
      })
      templates.map((template, index) => {
        setValue(`template.${index}`, {
          language: template.language,
          code: [
            {
              id: index,
              text: template.code[0].text ?? '',
              locked: false
            }
          ]
        })
      })
    }
  }, [watchedLanguages])

  const [createProblem, { error }] = useMutation(CREATE_PROBLEM)
  const onSubmit = async (input: CreateProblemInput) => {
    setIsCreating(true)
    await createProblem({
      variables: {
        groupId: 1,
        input
      }
    })
    if (error) {
      toast.error('Failed to create problem')
      setIsCreating(false)
      return
    }
    toast.success('Problem created successfully')
    router.push('/admin/problem')
    router.refresh()
  }

  const addExample = (type: 'samples' | 'testcases') => {
    setValue(type, [...getValues(type), { input: '', output: '' }])
  }

  const removeExample = (type: 'samples' | 'testcases', index: number) => {
    const currentValues = getValues(type)
    if (currentValues.length === 1) {
      toast.warning(
        `At least one ${type === 'samples' ? 'sample' : 'testcase'} is required`
      )
      return
    }
    const updatedValues = currentValues.filter((_, i) => i !== index)
    setValue(type, updatedValues)
  }

  return (
    <ScrollArea className="shrink-0">
      <main className="flex flex-col gap-6 px-20 py-16">
        <div className="flex items-center gap-4">
          <Link href="/admin/problem">
            <FaAngleLeft className="h-12 hover:text-gray-700/80" />
          </Link>
          <span className="text-4xl font-bold">Create Problem</span>
        </div>

        <form
          onSubmit={handleSubmit(onSubmit)}
          className="flex w-[760px] flex-col gap-6"
        >
          <div className="flex gap-6">
            <div className="flex flex-col gap-1">
              <Label>Title</Label>
              <Input
                id="title"
                type="text"
                placeholder="Name your problem"
                className={cn(inputStyle, 'w-[380px]')}
                {...register('title')}
              />
              {errors.title && (
                <div className="flex items-center gap-1 text-xs text-red-500">
                  <PiWarningBold />
                  {getValues('title').length === 0
                    ? 'required'
                    : errors.title.message}
                </div>
              )}
            </div>
            <div className="flex flex-col gap-4">
              <div className="flex items-center gap-2">
                <Label>Visible</Label>
                <Popover>
                  <PopoverTrigger asChild>
                    <button>
                      <MdHelpOutline className="text-gray-400 hover:text-gray-700" />
                    </button>
                  </PopoverTrigger>
                  <PopoverContent side="top" className="mb-2 px-4 py-3">
                    <ul className="text-sm font-normal leading-none">
                      <li>For contest, &apos;hidden&apos; is recommended.</li>
                      <li>You can edit these settings later.</li>
                    </ul>
                  </PopoverContent>
                </Popover>
              </div>

              <div className="flex items-center gap-2">
                <Controller
                  control={control}
                  name="isVisible"
                  render={({ field: { onChange, value } }) => (
                    <div className="flex gap-6">
                      <label className="flex gap-2">
                        <input
                          type="radio"
                          onChange={() => onChange(true)}
                          checked={value}
                          className="accent-black"
                        />
                        <FaEye
                          className={
                            value === true ? 'text-black' : 'text-gray-400'
                          }
                        />
                      </label>
                      <label className="flex gap-2">
                        <input
                          type="radio"
                          onChange={() => onChange(false)}
                          checked={value === false}
                          className="accent-black"
                        />
                        <FaEyeSlash
                          className={
                            value === false ? 'text-black' : 'text-gray-400'
                          }
                        />
                      </label>
                    </div>
                  )}
                />
              </div>
              {errors.isVisible && (
                <div className="flex items-center gap-1 text-xs text-red-500">
                  <PiWarningBold />
                  required
                </div>
              )}
            </div>
          </div>

          <div className="flex flex-col gap-1">
            <Label>Info</Label>
            <div className="flex gap-4">
              <div className="flex flex-col gap-1">
                <Controller
                  render={({ field }) => (
                    <OptionSelect
                      options={levels}
                      value={field.value}
                      onChange={field.onChange}
                    />
                  )}
                  name="difficulty"
                  control={control}
                />
                {errors.difficulty && (
                  <div className="flex items-center gap-1 text-xs text-red-500">
                    <PiWarningBold />
                    required
                  </div>
                )}
              </div>
              <div className="flex flex-col gap-1">
                <Controller
                  render={({ field }) => (
                    <CheckboxSelect
                      title="Language"
                      options={languages}
                      onChange={(selectedLanguages) => {
                        field.onChange(selectedLanguages)
                      }}
                    />
                  )}
                  name="languages"
                  control={control}
                />
                {errors.languages && (
                  <div className="flex items-center gap-1 text-xs text-red-500">
                    <PiWarningBold />
                    required
                  </div>
                )}
              </div>
              <div className="flex flex-col gap-1">
                <Controller
                  render={({ field }) => (
                    <TagsSelect options={tags} onChange={field.onChange} />
                  )}
                  name="tagIds"
                  control={control}
                />
                {errors.tagIds && (
                  <div className="flex items-center gap-1 text-xs text-red-500">
                    <PiWarningBold />
                    required
                  </div>
                )}
              </div>
            </div>
          </div>

          <div className="flex flex-col gap-1">
            <Label>Description</Label>
            <Controller
              render={({ field }) => (
                <TextEditor
                  placeholder="Enter a description..."
                  onChange={field.onChange}
                />
              )}
              name="description"
              control={control}
            />
            {errors.description && (
              <div className="flex items-center gap-1 text-xs text-red-500">
                <PiWarningBold />
                required
              </div>
            )}
          </div>

          <div className="flex flex-col gap-1">
            <div className="flex justify-between">
              <div className="flex w-[360px] flex-col gap-1">
                <Label>Input Description</Label>
                <Controller
                  render={({ field }) => (
                    <TextEditor
                      placeholder="Enter a description..."
                      onChange={field.onChange}
                    />
                  )}
                  name="inputDescription"
                  control={control}
                />
                {errors.inputDescription && (
                  <div className="flex items-center gap-1 text-xs text-red-500">
                    <PiWarningBold />
                    required
                  </div>
                )}
              </div>
              <div className="flex w-[360px] flex-col gap-1">
                <Label>Output Description</Label>
                <Controller
                  render={({ field }) => (
                    <TextEditor
                      placeholder="Enter a description..."
                      onChange={field.onChange}
                    />
                  )}
                  name="outputDescription"
                  control={control}
                />
                {errors.outputDescription && (
                  <div className="flex items-center gap-1 text-xs text-red-500">
                    <PiWarningBold />
                    required
                  </div>
                )}
              </div>
            </div>
          </div>

          <div className="flex flex-col gap-1">
            <div className="flex items-center gap-2">
              <Label>Sample</Label>
              <Badge
                onClick={() => addExample('samples')}
                className="h-[18px] w-[45px] cursor-pointer items-center justify-center bg-gray-200/60 p-0 text-xs font-medium text-gray-500 shadow-sm hover:bg-gray-200"
              >
                + add
              </Badge>
            </div>
            <div className="flex flex-col gap-2">
              {watchedSamples &&
                watchedSamples.map((_sample, index) => (
                  <div key={index} className="flex flex-col gap-1">
                    <ExampleTextarea
                      onRemove={() => removeExample('samples', index)}
                      inputName={`samples.${index}.input`}
                      outputName={`samples.${index}.output`}
                      register={register}
                    />
                    {errors.samples?.[index] && (
                      <div className="flex items-center gap-1 text-xs text-red-500">
                        <PiWarningBold />
                        required
                      </div>
                    )}
                  </div>
                ))}
            </div>
          </div>

          <div className="flex flex-col gap-1">
            <div className="flex items-center gap-2">
              <Label>Testcase</Label>
              <Badge
                onClick={() => addExample('testcases')}
                className="h-[18px] w-[45px] cursor-pointer items-center justify-center bg-gray-200/60 p-0 text-xs font-medium text-gray-500 shadow-sm hover:bg-gray-200"
              >
                + add
              </Badge>
            </div>
            <div className="flex flex-col gap-2">
              {watchedTestcases &&
                watchedTestcases.map((_testcase, index) => (
                  <div key={index} className="flex flex-col gap-1">
                    <ExampleTextarea
                      key={index}
                      onRemove={() => removeExample('testcases', index)}
                      inputName={`testcases.${index}.input`}
                      outputName={`testcases.${index}.output`}
                      register={register}
                    />
                    {errors.testcases?.[index] && (
                      <div className="flex items-center gap-1 text-xs text-red-500">
                        <PiWarningBold />
                        required
                      </div>
                    )}
                  </div>
                ))}
            </div>
          </div>

          <div className="flex flex-col gap-1">
            <Label>Limit</Label>
            <div className="flex gap-8">
              <div className="flex flex-col gap-1">
                <div className="flex items-center gap-2">
                  <Input
                    id="time"
                    type="number"
                    min={0}
                    placeholder="Time"
                    className={cn(inputStyle, 'h-[36px] w-[112px]')}
                    {...register('timeLimit', {
                      setValueAs: (value: string) => parseInt(value, 10)
                    })}
                  />
                  <p className="text-sm font-bold text-gray-600">ms</p>
                </div>
                {errors.timeLimit && (
                  <div className="flex items-center gap-1 text-xs text-red-500">
                    <PiWarningBold />
                    {Number.isNaN(getValues('timeLimit'))
                      ? 'required'
                      : errors.timeLimit?.message}
                  </div>
                )}
              </div>

              <div className="flex flex-col gap-1">
                <div className="flex items-center gap-2">
                  <Input
                    id="memory"
                    type="number"
                    min={0}
                    placeholder="Memory"
                    className={cn(inputStyle, 'h-[36px] w-[112px]')}
                    {...register('memoryLimit', {
                      setValueAs: (value: string) => parseInt(value, 10)
                    })}
                  />
                  <p className="text-sm font-bold text-gray-600">MB</p>
                </div>
                {errors.memoryLimit && (
                  <div className="flex items-center gap-1 text-xs text-red-500">
                    <PiWarningBold />
                    {Number.isNaN(getValues('memoryLimit'))
                      ? 'required'
                      : errors.memoryLimit?.message}
                  </div>
                )}
              </div>
            </div>
          </div>

          <div className="flex flex-col gap-1">
            <div className="flex items-center gap-2">
              <Label required={false}>Hint</Label>
              <Switch
                onCheckedChange={() => {
                  setShowHint(!showHint)
                  setValue('hint', '')
                }}
                checked={showHint}
                className="data-[state=checked]:bg-black data-[state=unchecked]:bg-gray-300"
              />
            </div>
            {showHint && (
              <Textarea
                id="hint"
                placeholder="Enter a hint"
                className="min-h-[120px] w-[760px] bg-white"
                {...register('hint')}
              />
            )}
          </div>

          <div className="flex flex-col gap-1">
            <div className="flex items-center gap-2">
              <Label required={false}>Source</Label>
              <Switch
                onCheckedChange={() => {
                  setShowSource(!showSource)
                  setValue('source', '')
                }}
                checked={showSource}
                className="data-[state=checked]:bg-black data-[state=unchecked]:bg-gray-300"
              />
            </div>
            {showSource && (
              <Input
                id="source"
                type="text"
                placeholder="Enter a source"
                className={cn(inputStyle, 'h-[36px] w-[380px]')}
                {...register('source')}
              />
            )}
          </div>

          <div className="flex flex-col gap-6">
            {watchedLanguages &&
              watchedLanguages.map((language, index) => (
                <div key={index} className="flex gap-4">
                  <div className="flex flex-col gap-1">
                    <div className="flex items-center gap-2">
                      <Label required={false}>{language} Template</Label>
                    </div>
                    {language && (
                      <Textarea
                        placeholder={`Enter a ${language} template...`}
                        className="h-[180px] w-[480px] bg-white"
                        {...register(`template.${index}.code.0.text`)}
                      />
                    )}
                  </div>
                </div>
              ))}
          </div>
          <Button
            type="submit"
            className="flex h-[36px] w-[100px] items-center gap-2 px-0"
            disabled={isCreating}
          >
            <IoMdCheckmarkCircleOutline fontSize={20} />
            <div className="mb-[2px] text-base">Create</div>
          </Button>
        </form>
      </main>
      <ScrollBar orientation="horizontal" />
    </ScrollArea>
  )
}

// frontend/src/admin/pages/[groupId]/problem/create.vue
<script setup lang="ts">
/* eslint-disable @typescript-eslint/naming-convention */
import Button from '@/common/components/Atom/Button.vue'
import InputItem from '@/common/components/Atom/InputItem.vue'
import TextEditor from '@/common/components/Organism/TextEditor.vue'
import { useToast } from '@/common/composables/toast'
import type { Language, Level } from '@/user/problem/types'
import { toTypedSchema } from '@vee-validate/zod'
import { useMutation } from '@vue/apollo-composable'
import { gql } from 'graphql-tag'
import { useFieldArray, useForm, Field } from 'vee-validate'
import { useRouter } from 'vue-router'
import { z } from 'zod'
import IconLeft from '~icons/fa6-solid/angle-left'
import IconTrash from '~icons/fa/trash-o'

const router = useRouter()
const schema = z.object({
  title: z.string().min(1),
  description: z.string(),
  inputDescription: z.string(),
  outputDescription: z.string(),
  hint: z.string().default(''),
  source: z.string().default(''),
  template: z
    .array(
      z.object({
        language: z.enum(['C', 'Cpp', 'Python3', 'Java']),
        code: z.array(
          z.object({
            id: z.number(),
            text: z.string(),
            locked: z.boolean()
          })
        )
      })
    )
    .default([]),
  languages: z
    .array(z.enum(['C', 'Cpp', 'Python3', 'Java']))
    .min(1, 'At least one language is required.')
    .default([]),
  timeLimit: z
    .string()
    .default('2000')
    .transform((v) => parseInt(v)),
  memoryLimit: z
    .string()
    .default('512')
    .transform((v) => parseInt(v)),
  difficulty: z
    .enum(['Level1', 'Level2', 'Level3', 'Level4', 'Level5'])
    .default('Level1'),
  inputExamples: z.array(z.string()).default(['']),
  outputExamples: z.array(z.string()).default(['']),
  testcases: z
    .array(
      z.object({
        input: z.string(),
        output: z.string(),
        scoreWeight: z.number().optional()
      })
    )
    .default([{ input: '', output: '' }]),
  tagIds: z.array(z.number()).default([])
})

const {
  defineInputBinds,
  defineComponentBinds,
  setFieldValue,
  values,
  errors,
  handleSubmit,
  resetForm
} = useForm({
  validationSchema: toTypedSchema(schema)
})

const title = defineComponentBinds('title')
const difficulty = defineInputBinds('difficulty')
const description = defineComponentBinds('description')
const inputDescription = defineInputBinds('inputDescription')
const outputDescription = defineInputBinds('outputDescription')
const timeLimit = defineComponentBinds('timeLimit')
const memoryLimit = defineComponentBinds('memoryLimit')
const hint = defineComponentBinds('hint')

const inputExamples = useFieldArray('inputExamples')
const outputExamples = useFieldArray('outputExamples')
const testcases = useFieldArray('testcases')

const toast = useToast()

const { mutate, onError, onDone } = useMutation(gql`
  mutation CreateProblem($input: CreateProblemInput!) {
    createProblem(input: $input) {
      id
    }
  }
`)

onError(() => {
  toast({
    message: 'Failed to create problem',
    type: 'error'
  })
})

onDone(() => {
  toast({
    message: 'Created problem successfully',
    type: 'success'
  })
  resetForm()
  router.go(-1)
})

const submit = handleSubmit(
  (input) => {
    mutate({ input })
  },
  (error) => {
    const key = Object.keys(error.errors)[0]
    const message = `Invalid ${key}: ` + Object.values(error.errors)[0]
    toast({ message, type: 'error' })
  }
)

const levelLabels: Record<Level, string> = {
  Level1: 'Level 1',
  Level2: 'Level 2',
  Level3: 'Level 3',
  Level4: 'Level 4',
  Level5: 'Level 5'
}

const languageLabels: Record<Language, string> = {
  C: 'C',
  Cpp: 'C++',
  Python3: 'Python3',
  Java: 'Java'
}

const toggleLanguage = (language: Language) => {
  if (values.languages?.includes(language)) {
    setFieldValue(
      'languages',
      values.languages.filter((l) => l !== language)
    )
  } else {
    setFieldValue(
      'languages',
      values.languages ? [...values.languages, language] : [language]
    )
  }
}

const addExample = () => {
  inputExamples.push('')
  outputExamples.push('')
}

const removeExample = (index: number) => {
  inputExamples.remove(index)
  outputExamples.remove(index)
}
</script>

<template>
  <div
    class="text-gray-dark/40 flex w-fit cursor-pointer items-center gap-1 rounded hover:opacity-60"
    @click="$router.go(-1)"
  >
    <IconLeft />
    Back
  </div>
  <form
    class="flex w-[80%] flex-col justify-center gap-8"
    @submit.prevent="submit"
  >
    <h1 class="text-gray-dark mt-2 text-2xl font-semibold">Create Problem</h1>
    <div class="col-span-3">
      <label class="text-lg font-bold">
        Title
        <span class="text-red">*</span>
      </label>
      <InputItem
        v-bind="title"
        class="mt-3 w-full"
        placeholder="Title"
        :error="errors.title"
      />
    </div>
    <div class="flex justify-between gap-5">
      <div class="flex flex-1 flex-col gap-3">
        <label class="text-lg font-bold">
          Difficulty
          <span class="text-red">*</span>
        </label>
        <select
          id="difficulty"
          v-bind="difficulty"
          name="difficulty"
          class="border-gray focus:border-green focus:ring-green w-full rounded border px-3 py-1 outline-none focus:ring-1"
        >
          <option
            v-for="(label, value) in levelLabels"
            :key="value"
            :value="value"
          >
            {{ label }}
          </option>
        </select>
      </div>
      <div class="flex flex-1 flex-col gap-3">
        <label class="text-lg font-bold">
          Language
          <span class="text-red">*</span>
        </label>
        <div class="flex gap-3">
          <button
            v-for="(label, value) in languageLabels"
            :key="value"
            type="button"
            class="rounded px-3 py-1 font-medium"
            :class="
              values.languages?.includes(value)
                ? 'bg-blue hover:bg-blue/90 text-white'
                : 'bg-gray/25 hover:bg-gray/40 text-text/50'
            "
            @click="toggleLanguage(value)"
          >
            {{ label }}
          </button>
        </div>
        <p class="text-red text-xs">{{ errors.languages }}</p>
      </div>
    </div>
    <div>
      <h2 class="mb-3 text-lg font-bold">
        Description
        <span class="text-red">*</span>
      </h2>
      <TextEditor v-bind="description" size="lg" />
    </div>
    <div class="grid grid-cols-2 gap-5">
      <div>
        <label class="mb-3 text-lg font-bold">
          Input Description
          <span class="text-red">*</span>
        </label>
        <textarea
          v-bind="inputDescription"
          class="border-gray focus:border-green focus:ring-green mt-3 h-[120px] w-full resize-none rounded-lg outline-none focus:ring-1"
        />
      </div>
      <div>
        <label class="text-lg font-bold">
          Output Description
          <span class="text-red">*</span>
        </label>
        <textarea
          v-bind="outputDescription"
          class="border-gray focus:border-green focus:ring-green mt-3 h-[120px] w-full resize-none rounded-lg outline-none focus:ring-1"
        />
      </div>
    </div>
    <div class="grid grid-cols-2 gap-5">
      <div>
        <label class="mb-3 text-lg font-bold">
          Time Limit (ms)
          <span class="text-red">*</span>
        </label>
        <InputItem
          v-bind="timeLimit"
          placeholder="Time Limit (ms)"
          class="mt-3 w-full"
          type="number"
        />
      </div>
      <div>
        <label class="mb-3 text-lg font-bold">
          Memory Limit (MB)
          <span class="text-red">*</span>
        </label>
        <InputItem
          v-bind="memoryLimit"
          placeholder="Memory Limit (MB)"
          class="mt-3 w-full"
          type="number"
        />
      </div>
    </div>
    <div>
      <h2 class="mb-3 text-lg font-bold">Hint</h2>
      <TextEditor v-bind="hint" size="lg" />
    </div>
    <div
      v-for="(_, index) in inputExamples.fields.value"
      :key="index"
      class="flex flex-col gap-5"
    >
      <div class="flex justify-between">
        <h2 class="text-lg font-bold">
          Sample {{ index + 1 }}
          <span class="text-red">*</span>
        </h2>
        <Button
          v-if="inputExamples.fields.value.length > 1"
          type="button"
          class="flexitems-center justify-center gap-2"
          @click="removeExample(index)"
        >
          <IconTrash />
          Delete
        </Button>
      </div>
      <div class="rounded-lg bg-slate-50 bg-opacity-50 p-5">
        <div class="grid grid-cols-2 gap-5">
          <div>
            <label class="text-gray-dark mb-3 text-lg font-bold">
              Input Sample
            </label>
            <Field
              as="textarea"
              name="`inputExamples[${index}]`"
              class="border-gray focus:border-green focus:ring-green mt-3 h-[180px] w-full resize-none rounded-lg font-mono outline-none focus:ring-1"
            />
          </div>
          <div>
            <label class="text-gray-dark text-lg font-bold">
              Output Sample
            </label>
            <Field
              as="textarea"
              name="`outputExamples[${index}]`"
              class="border-gray focus:border-green focus:ring-green mt-3 h-[180px] w-full resize-none rounded-lg font-mono outline-none focus:ring-1"
            />
          </div>
        </div>
      </div>
    </div>
    <Button
      type="button"
      class="border-gray text-gray-dark flex h-[45px] items-center justify-center border"
      color="white"
      @click="addExample"
    >
      Add Sample
    </Button>
    <div
      v-for="(_, index) in testcases.fields.value"
      :key="index"
      class="flex flex-col gap-5"
    >
      <div class="flex justify-between">
        <h2 class="text-lg font-bold">
          Testcase {{ index + 1 }}
          <span class="text-red">*</span>
        </h2>
        <Button
          v-if="testcases.fields.value.length > 1"
          type="button"
          class="flex h-[32px] items-center justify-center gap-2"
          @click="testcases.remove(index)"
        >
          <IconTrash />
          Delete
        </Button>
      </div>
      <div class="rounded-lg bg-slate-50 bg-opacity-50 p-5">
        <div class="grid grid-cols-2 gap-5">
          <div>
            <label class="text-gray-dark mb-3 text-lg font-bold">
              Input Testcase
            </label>
            <Field
              as="textarea"
              name="`testcases[${index}].input`"
              class="border-gray focus:border-green focus:ring-green mt-3 h-[180px] w-full resize-none rounded-lg font-mono outline-none focus:ring-1"
            />
          </div>
          <div>
            <label class="text-gray-dark text-lg font-bold">
              Output Testcase
            </label>
            <Field
              as="textarea"
              name="`testcases[${index}].output`"
              class="border-gray focus:border-green focus:ring-green mt-3 h-[180px] w-full resize-none rounded-lg font-mono outline-none focus:ring-1"
            />
          </div>
        </div>
      </div>
    </div>
    <Button
      type="button"
      class="border-gray text-gray-dark flex h-[45px] items-center justify-center border"
      color="white"
      @click="testcases.push({ input: '', output: '' })"
    >
      Add Testcase
    </Button>
    <div class="flex justify-end gap-3 py-5">
      <Button type="button" color="gray-dark">Cancel</Button>
      <Button type="submit">Create</Button>
    </div>
  </form>
</template>

<route lang="yaml">
meta:
  layout: admin
</route>
