// frontend/src/user/home/components/Carousel.vue
<script setup lang="ts">
import { useIntervalFn } from '@vueuse/core'
import { ref } from 'vue'
import Fa6SolidAngleLeft from '~icons/fa6-solid/angle-left'
import Fa6SolidAngleRight from '~icons/fa6-solid/angle-right'

interface Slide {
  topTitle: string
  bottomTitle: string
  sub: string
  img: string
  imgAlt: string
  color: 'green' | 'black' | 'white' | 'yellow'
  href: string
}
const props = defineProps<{ slides: Slide[] }>()

const bgColors: { [key: string]: string } = {
  green: 'bg-[#2e4e3f]',
  black: 'bg-[#333333]',
  white: 'bg-[#ffffff]',
  yellow: 'bg-[#f9de4a]'
}
const textColors: { [key: string]: string } = {
  green: 'text-white',
  black: 'text-white',
  white: 'text-black',
  yellow: 'text-black'
}

const currentSlideIndex = ref(0)
const { pause, resume } = useIntervalFn(() => {
  currentSlideIndex.value = (currentSlideIndex.value + 1) % props.slides.length
}, 5000)

const clickLeft = () => {
  currentSlideIndex.value =
    (currentSlideIndex.value - 1 + props.slides.length) % props.slides.length
  pause()
  resume()
}

const clickRight = () => {
  currentSlideIndex.value = (currentSlideIndex.value + 1) % props.slides.length
  pause()
  resume()
}
</script>

<template>
  <div
    class="relative h-[400px] overflow-hidden rounded-3xl"
    :class="bgColors[slides[currentSlideIndex].color]"
  >
    <div class="absolute bottom-0 left-0 right-0 z-50 mb-3 flex justify-center">
      <div
        class="flex items-center justify-center gap-2 rounded-full bg-black bg-opacity-70 px-3 py-1.5 text-sm font-bold text-white"
      >
        <button class="opacity-70 hover:opacity-100" @click="clickLeft">
          <Fa6SolidAngleLeft class="text-xs" />
        </button>
        <p class="flex gap-1">
          <span>{{ currentSlideIndex + 1 }}</span>
          <span class="font-thin text-slate-300">/</span>
          <span>{{ slides.length }}</span>
        </p>
        <button class="opacity-70 hover:opacity-100" @click="clickRight">
          <Fa6SolidAngleRight class="text-xs" />
        </button>
      </div>
    </div>
    <RouterLink :to="slides[currentSlideIndex].href">
      <div
        v-for="(item, index) in slides"
        :key="index"
        class="absolute left-0 top-0 flex h-full w-full justify-center opacity-0 transition-opacity duration-1000 ease-in-out"
        :class="`${index === currentSlideIndex && 'opacity-100'} ${
          bgColors[item.color]
        }`"
      >
        <div
          class="flex w-full max-w-7xl flex-col-reverse justify-between gap-5 p-8 py-14 md:flex-row md:items-center md:px-16 md:py-0"
        >
          <div class="flex flex-col items-start justify-center md:gap-5">
            <div :class="textColors[item.color]">
              <p
                class="mb-2 whitespace-nowrap text-2xl font-semibold md:text-3xl"
              >
                {{ item.topTitle }}
              </p>
              <p
                class="mb-2 whitespace-nowrap text-2xl font-semibold md:text-3xl"
              >
                {{ item.bottomTitle }}
              </p>
            </div>
            <p class="md:text-lg" :class="textColors[item.color]">
              {{ item.sub }}
            </p>
          </div>
          <img
            :src="item.img"
            :alt="item.imgAlt"
            class="h-[200px] object-contain md:h-[350px]"
          />
        </div>
      </div>
    </RouterLink>
  </div>
</template>

// apps/frontend/app/(main)/_components/Carousel.tsx
'use client'

import { Button } from '@/components/ui/button'
import { cn } from '@/lib/utils'
import type { Route } from 'next'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { FaAngleLeft, FaAngleRight } from 'react-icons/fa6'

interface Props {
  slides: {
    type: string
    topTitle: string
    bottomTitle: string
    sub: string
    img: string
    imgAlt: string
    href: string
  }[]
}

const bgColors: { [key: string]: string } = {
  codedang: 'bg-gradient-to-r from-[#3D63B8] to-[#0E1322]',
  github: 'bg-gradient-to-b from-[#161429] to-[#704FC3]',
  skkuding: 'bg-gradient-to-r from-[#41775D] to-[#123D29]'
}

export default function Carousel({ slides }: Props) {
  const [facade, setFacade] = useState(0)

  useEffect(() => {
    const timer = setTimeout(() => {
      setFacade((facade + 1) % slides.length)
    }, 5000)
    return () => clearTimeout(timer)
  }, [facade, slides])

  const handleClick = (next: number) => {
    setFacade(next % slides.length)
  }

  return (
    <div className="relative my-5 h-[466px] w-full overflow-hidden rounded-lg bg-gray-100 sm:h-[360px]">
      {slides.map((slide, index) => (
        <Link
          href={slide.href as Route}
          key={slide.href + slide.topTitle}
          className={cn(
            'absolute inset-0 z-10 flex flex-col-reverse items-center justify-between py-14 pl-6 text-white transition-opacity duration-1000 ease-in-out sm:flex-row md:pl-10',
            facade !== index && 'z-0 opacity-0',
            bgColors[slide.type]
          )}
        >
          <div className="mb-10 w-full text-4xl font-bold">
            <p className="font-mono md:text-nowrap">{slide.topTitle}</p>
            <p className="font-mono md:text-nowrap">{slide.bottomTitle}</p>
            <p className="mt-4 whitespace-nowrap text-base font-normal opacity-70 md:text-lg">
              {slide.sub}
            </p>
          </div>
          <div>
            <Image
              src={slide.img}
              alt={slide.imgAlt}
              width={554}
              height={554}
              className="absolute -right-16 bottom-48 z-[-10] mr-5 size-[330px] object-contain sm:relative sm:bottom-0 sm:left-0 sm:size-[1024px] sm:pl-0"
              priority
            />
          </div>
        </Link>
      ))}
      <div className="absolute bottom-4 left-0 right-0 z-20 flex justify-center">
        <div className="flex h-7 items-center rounded-full bg-white/60 px-2.5">
          <Button
            variant="ghost"
            className="px-0 hover:bg-transparent active:bg-transparent"
            onClick={() => handleClick(facade - 1 + slides.length)}
          >
            <FaAngleLeft className="h-4 fill-black opacity-70 hover:opacity-100" />
          </Button>
          <p className="mx-1 flex gap-1 text-sm text-black">
            <span>{facade + 1}</span>
            <span className="opacity-70">/</span>
            <span>{slides.length}</span>
          </p>
          <Button
            variant="ghost"
            className="px-0 hover:bg-transparent active:bg-transparent"
            onClick={() => handleClick(facade + 1)}
          >
            <FaAngleRight className="h-4 fill-black opacity-70 hover:opacity-100" />
          </Button>
        </div>
      </div>
    </div>
  )
}
