// frontend-client/components/ui/badge.tsx
import { cn } from '@/lib/utils'
import { cva, type VariantProps } from 'class-variance-authority'
import * as React from 'react'

const badgeVariants = cva(
  'inline-flex items-center rounded-full border border-gray-200 px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-gray-950 focus:ring-offset-2 dark:border-gray-800 dark:focus:ring-gray-300',
  {
    variants: {
      variant: {
        default:
          'border-transparent bg-gray-200 text-blue-400 hover:bg-gray-900/80',
        secondary:
          'border-transparent bg-gray-100 text-gray-900 hover:bg-gray-100/80 dark:bg-gray-800 dark:text-gray-50 dark:hover:bg-gray-800/80',
        destructive:
          'border-transparent bg-red-500 text-gray-50 hover:bg-red-500/80 dark:bg-red-900 dark:text-gray-50 dark:hover:bg-red-900/80',
        outline: 'text-gray-950 dark:text-gray-50'
      }
    },
    defaultVariants: {
      variant: 'default'
    }
  }
)

export interface BadgeProps
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof badgeVariants> {}

const Badge = ({ className, variant, ...props }: BadgeProps) => {
  return (
    <div className={cn(badgeVariants({ variant }), className)} {...props} />
  )
}

export { Badge, badgeVariants }

// frontend/src/common/components/Molecule/Badge.vue
<script setup lang="ts">
defineProps<{
  color: 'red' | 'green' | 'blue'
}>()

const colorMapper = {
  red: 'bg-red',
  green: 'bg-green',
  blue: 'bg-blue'
}
</script>

<template>
  <div
    class="border-gray bg-gray-light flex h-8 w-fit items-center rounded-md border px-2"
  >
    <div :class="colorMapper[color]" class="mx-1 h-4 w-4 rounded-full" />
    <div class="text-gray-dark mx-2 font-bold">
      <slot />
    </div>
  </div>
</template>
