// frontend/src/home/components/Carousel.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useIntervalFn } from '@vueuse/core'

const props = defineProps<{
  slides: string[]
}>()

const currentSlide = ref(0)
const direction = ref<'right' | 'left'>('right')

const switchSlide = (index: number) => {
  direction.value = index - currentSlide.value > 0 ? 'right' : 'left'
  currentSlide.value = index
  resume()
}

const { pause, resume } = useIntervalFn(() => {
  switchSlide((currentSlide.value + 1) % props.slides.length)
}, 5000)
</script>

<template>
  <div class="flex justify-center">
    <div class="relative h-[600px] w-full overflow-hidden">
      <div class="absolute left-1/2 bottom-5 z-10 -translate-x-1/2">
        <button
          v-for="index in slides.length"
          :key="index"
          class="m-1 h-4 w-4 cursor-pointer rounded-full border-none bg-white opacity-50"
          :class="currentSlide === index - 1 ? 'opacity-100' : ''"
          @click="switchSlide(index - 1)"
          @mouseenter="pause"
          @mouseout="resume"
        ></button>
      </div>
      <transition
        class="absolute inset-0"
        enter-active-class="transition-transform duration-1000"
        leave-active-class="transition-transform duration-1000"
        :enter-from-class="
          direction === 'right' ? 'translate-x-full' : '-translate-x-full'
        "
        :leave-to-class="
          direction === 'right' ? '-translate-x-full' : 'translate-x-full'
        "
        @mouseenter="pause"
        @mouseout="resume"
      >
        <img
          :key="currentSlide"
          class="h-full w-full"
          :src="slides[currentSlide]"
        />
      </transition>
    </div>
  </div>
</template>

// frontend-client/app/_components/Carousel.tsx
'use client'

import { Button } from '@/components/ui/button'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { FaAngleLeft, FaAngleRight } from 'react-icons/fa6'

interface Props {
  slides: { href: string }[]
}

export default function Carousel({ slides }: Props) {
  const [facade, setFacade] = useState(0)

  useEffect(() => {
    const timer = setTimeout(() => {
      setFacade((facade + 1) % slides.length)
    }, 5000)
    return () => clearTimeout(timer)
  }, [facade, slides])

  const handleClick = (next: number) => {
    setFacade(next % slides.length)
  }

  return (
    <div className="relative h-80 w-full overflow-hidden rounded-3xl bg-gray-100">
      <Link href={new URL(slides[facade].href)}>
        {slides.map((_, index) => (
          <div
            key={index}
            className={`absolute left-0 top-0 h-full w-full transition-opacity duration-1000 ease-in-out ${
              facade !== index && ' opacity-0'
            }`}
          >
            {/* TODO: 슬라이드 데이터 삽입*/}
          </div>
        ))}
      </Link>
      <div className="absolute bottom-5 left-0 right-0 flex justify-center bg-opacity-70">
        <div className="z-10 flex h-7 items-center rounded-full bg-gray-900 px-2.5">
          <Button
            variant="ghost"
            className="px-0 hover:bg-transparent"
            onClick={() => handleClick(facade - 1 + slides.length)}
          >
            <FaAngleLeft className="h-4 fill-white opacity-70 hover:opacity-100" />
          </Button>
          <p className="mx-1 flex gap-1 text-sm text-white">
            <span>{facade + 1}</span>
            <span className="font-thin opacity-70">/</span>
            <span>{slides.length}</span>
          </p>
          <Button
            variant="ghost"
            className="px-0 hover:bg-transparent"
            onClick={() => handleClick(facade + 1)}
          >
            <FaAngleRight className="h-4 fill-white opacity-70 hover:opacity-100" />
          </Button>
        </div>
      </div>
    </div>
  )
}
