// frontend/src/components/Organism/Header.vue
<script setup lang="ts">
import Dropdown from '../Molecule/Dropdown.vue'
defineProps<{
  msg: string
}>()
interface data {
  isAuthenticated: boolean
  isAdminRole: boolean
}
const props: data = {
  isAuthenticated: true,
  isAdminRole: false
}
</script>

<template>
  <nav
    class="header-container sticky top-0 z-50 flex content-center items-center justify-between border-b-[1px] border-b-[#cdcdcd] bg-white px-12 py-4 font-medium opacity-95"
  >
    <a href="/">
      <img src="../../common/assets/signature.png" class="h-12 w-auto" />
    </a>
    <div>
      <a
        class="text-text-title hover:text-green active:text-green mr-4 text-2xl font-medium hover:no-underline"
        href="/announcement"
      >
        Notice
      </a>
      <a
        class="text-text-title hover:text-green mr-4 text-2xl font-medium hover:no-underline"
        href="/contest"
      >
        Contests
      </a>
      <a
        class="text-text-title hover:text-green mr-4 text-2xl font-medium hover:no-underline"
        href="/problem"
      >
        Problems
      </a>
      <a
        class="text-text-title hover:text-green mr-8 text-2xl font-medium hover:no-underline"
        href="/lecture"
      >
        Lecture
      </a>
    </div>
    <div>
      <Dropdown v-bind="props">
        <template #dropdown-icon></template>
        <template #dropdown-content></template>
      </Dropdown>
    </div>
  </nav>
</template>

// frontend-client/app/_components/Header.tsx
import CodedangLogo from '@/public/codedang.svg'
import Image from 'next/image'
import Link from 'next/link'
import HeaderAuthPanel from './HeaderAuthPanel'

export default function Header() {
  return (
    <header className="border-b-gray grid h-16 place-items-center border-b bg-white px-5">
      <div className="flex w-full max-w-7xl items-center justify-between gap-5">
        <div className="flex w-1/2 min-w-fit items-center justify-between gap-8">
          <Link href="/">
            <Image src={CodedangLogo} alt="코드당" width={90} />
          </Link>

          <nav className="hidden gap-8 capitalize md:flex">
            <Link href="/notice" className="text-lg hover:opacity-60">
              Notice
            </Link>
            <Link href="/contest" className="text-lg hover:opacity-60">
              Contest
            </Link>
            <Link href="/problem" className="text-lg hover:opacity-60">
              problem
            </Link>
            <Link href="/group" className="text-lg hover:opacity-60">
              Group
            </Link>
          </nav>
        </div>

        <HeaderAuthPanel />
      </div>
    </header>
  )
}
