// frontend/src/common/components/Organism/Signup.vue
<script setup lang="ts">
import Logo from '@/common/assets/codedang.svg'
import { useToast } from '@/common/composables/toast'
import { toTypedSchema } from '@vee-validate/zod'
import axios from 'axios'
import { AxiosError } from 'axios'
import { useForm } from 'vee-validate'
import { ref } from 'vue'
import { z } from 'zod'
import RegularEye from '~icons/fa6-regular/eye'
import EyeSlash from '~icons/fa6-regular/eye-slash'
import IconCheck from '~icons/fa6-solid/check'
import IconPaperPlane from '~icons/fa6-solid/paper-plane'
import Button from '../Atom/Button.vue'
import InputItem from '../Atom/InputItem.vue'

const emit = defineEmits<{
  (e: 'to', value: 'login' | 'signup' | 'password' | 'close'): void
}>()

const schema = z
  .object({
    username: z.string().min(3).max(10),
    email: z.string().email(),
    verificationCode: z.string().min(6).max(6),
    realName: z.string().min(1).max(20),
    password: z.string().min(8).max(32),
    passwordAgain: z.string().min(8).max(32)
  })
  .refine((data) => data.password === data.passwordAgain, {
    message: 'Passwords do not match',
    path: ['passwordAgain']
  })
  .refine((data) => /^[a-zA-Z0-9]+$/.test(data.username), {
    message: 'Username can only contain alphabets and numbers',
    path: ['username']
  })
  .refine((data) => /^[a-zA-Z\s]+$/.test(data.realName), {
    message: 'Real name can only contain alphabets',
    path: ['realName']
  })

const { defineComponentBinds, errors, validateField, handleSubmit } = useForm({
  validationSchema: toTypedSchema(schema)
})

const username = defineComponentBinds('username')
const email = defineComponentBinds('email')
const verificationCode = defineComponentBinds('verificationCode')
const realName = defineComponentBinds('realName')
const password = defineComponentBinds('password')
const passwordAgain = defineComponentBinds('passwordAgain')

const showPassword = ref(false)
const showPasswordAgain = ref(false)

const sentEmail = ref(false)
const emailVerified = ref(false)
const emailAuthToken = ref('')

const toast = useToast()

const signup = handleSubmit(async (input) => {
  try {
    await axios.post(
      '/api/user/sign-up',
      {
        username: input.username,
        email: input.email,
        realName: input.realName,
        password: input.password
      },
      // eslint-disable-next-line @typescript-eslint/naming-convention
      { headers: { 'email-auth': emailAuthToken.value } }
    )
    toast({
      message: 'Sign up succeed!',
      type: 'success'
    })
    emit('to', 'close')
  } catch (error) {
    toast({
      message: 'Sign up failed!',
      type: 'error'
    })
  }
})

const sendCodeToEmail = async () => {
  const emailIsValid = await validateField('email')
  if (!emailIsValid) {
    toast({
      message: 'Email is not valid!',
      type: 'error'
    })
    return
  }

  try {
    await axios.post('/api/email-auth/send-email/register-new', {
      email: email.value
    })
    sentEmail.value = true
  } catch (error) {
    if (error instanceof AxiosError && error.response?.status === 422) {
      toast({
        message: 'You have already signed up!',
        type: 'error'
      })
      return
    }
    toast({
      message: 'Sending verification code failed!',
      type: 'error'
    })
  }
}

const verifyCode = async () => {
  const emailIsValid = await validateField('email')
  if (!emailIsValid) {
    toast({
      message: 'Email is not valid!',
      type: 'error'
    })
    return
  }

  const verificationCodeIsValid = await validateField('verificationCode')
  if (!verificationCodeIsValid) {
    toast({
      message: 'Verification code is not valid!',
      type: 'error'
    })
    return
  }

  try {
    const response = await axios.post('/api/email-auth/verify-pin', {
      pin: verificationCode.value,
      email: email.value
    })
    if (response.status === 200) {
      emailVerified.value = true
      emailAuthToken.value = response.headers['email-auth']
    } else {
      toast({
        message: 'Email verification failed!',
        type: 'error'
      })
    }
  } catch (error) {
    toast({
      message: 'Email verification failed!',
      type: 'error'
    })
  }
}
</script>

<template>
  <div class="flex flex-col items-center justify-center">
    <img :src="Logo" class="mb-8 h-20" />
    <form class="flex w-60 flex-col gap-4" @submit.prevent="signup">
      <InputItem
        v-bind="username"
        placeholder="Username"
        :error="errors.username"
      />
      <div class="flex gap-2">
        <InputItem
          v-bind="email"
          type="email"
          placeholder="Email Address"
          :error="errors.email"
        />
        <Button color="blue" @click.prevent="sendCodeToEmail">
          <IconPaperPlane />
        </Button>
      </div>
      <p v-show="sentEmail" class="text-green text-xs font-bold">
        Email verification code has been sent!
      </p>
      <div class="flex gap-2">
        <InputItem
          v-bind="verificationCode"
          type="number"
          placeholder="Verification Code"
          :error="errors.verificationCode"
        />
        <Button color="blue" @click.prevent="verifyCode()">
          <IconCheck />
        </Button>
      </div>
      <p v-show="emailVerified" class="text-green text-xs font-bold">
        Email has been verified!
      </p>
      <InputItem
        :v-bind="realName"
        placeholder="Real Name"
        :error="errors.realName"
      />
      <div class="flex items-center justify-between">
        <InputItem
          :v-bind="password"
          placeholder="Password"
          :type="showPassword ? 'text' : 'password'"
          :error="errors.password"
        />
        <component
          :is="showPassword ? RegularEye : EyeSlash"
          @click.stop="showPassword = !showPassword"
        />
      </div>
      <div class="flex items-center justify-between">
        <InputItem
          v-bind="passwordAgain"
          placeholder="Password Check"
          :type="showPasswordAgain ? 'text' : 'password'"
          :error="errors.passwordAgain"
        />
        <component
          :is="showPasswordAgain ? RegularEye : EyeSlash"
          @click.stop="showPasswordAgain = !showPasswordAgain"
        />
      </div>
      <Button color="blue" type="submit">Register</Button>
    </form>
    <div class="text-gray-dark mt-6 flex flex-col items-center text-sm">
      Already have an account?
      <a
        class="text-gray-dark hover:text-gray-dark/80 active:text-gray-dark/60 w-fit cursor-pointer text-sm underline"
        @click="$emit('to', 'login')"
      >
        Log In
      </a>
    </div>
  </div>
</template>

// frontend-client/app/_components/SignUp.tsx
'use client'

import { Toaster } from '@/components/ui/toaster'
import { useToast } from '@/components/ui/use-toast'
import { baseUrl } from '@/lib/vars'
import CodedangLogo from '@/public/codedang.svg'
import { zodResolver } from '@hookform/resolvers/zod'
import Image from 'next/image'
import React, { useState } from 'react'
import { useForm } from 'react-hook-form'
import { FaPaperPlane } from 'react-icons/fa'
import { FaCheck } from 'react-icons/fa'
import { FaEyeSlash } from 'react-icons/fa'
import { FaEye } from 'react-icons/fa'
import { z } from 'zod'
import { Button } from '../../components/ui/button'
import { Input } from '../../components/ui/input'

interface SignUpFormInput {
  username: string
  email: string
  verificationCode: string
  realName: string
  password: string
  passwordAgain: string
}

const schema = z
  .object({
    username: z.string().min(3).max(10),
    email: z.string().email(),
    verificationCode: z.string().min(6).max(6),
    realName: z.string().min(1).max(20),
    password: z.string().min(8).max(32),
    passwordAgain: z.string().min(8).max(32)
  })
  .refine(
    (data: { password: string; passwordAgain: string }) =>
      data.password === data.passwordAgain,
    {
      message: 'Passwords do not match',
      path: ['passwordAgain']
    }
  )
  .refine(
    (data: { username: string }) => /^[a-zA-Z0-9]+$/.test(data.username),
    {
      message: 'Username can only contain alphabets and numbers',
      path: ['username']
    }
  )
  .refine((data: { realName: string }) => /^[a-zA-Z\s]+$/.test(data.realName), {
    message: 'Real name can only contain alphabets',
    path: ['realName']
  })

export default function SignUp() {
  const [sentEmail, setSentEmail] = useState<boolean>(false)
  const [emailVerified, setEmailVerified] = useState<boolean>(false)
  const [emailAuthToken, setEmailAuthToken] = useState<string>('')
  const [passwordShow, setPasswordShow] = useState<boolean>(false)
  const [passwordAgainShow, setPasswordAgainShow] = useState<boolean>(false)

  const {
    handleSubmit,
    register,
    getValues,
    formState: { errors }
  } = useForm<SignUpFormInput>({
    resolver: zodResolver(schema)
  })

  const { toast } = useToast()

  const onSubmit = async (data: {
    username: string
    email: string
    realName: string
    password: string
  }) => {
    try {
      await fetch(baseUrl + '/user/sign-up', {
        method: 'POST',
        headers: {
          'email-auth': emailAuthToken,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          username: data.username,
          email: data.email,
          realName: data.realName,
          password: data.password
        })
      })
      toast({
        description: 'Sign up succeed!',
        className: 'text-blue-500'
      })
    } catch (error) {
      toast({
        description: 'Sign up failed!',
        className: 'text-red-500'
      })
    }
  }

  const sendCodeToEmail = async (email: string) => {
    if (!sentEmail) {
      await fetch(baseUrl + '/email-auth/send-email/register-new', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          email: email
        })
      })
        .then((res) => {
          if (res.status === 409) {
            toast({
              description: 'You have already signed up!',
              className: 'text-red-500'
            })
          } else if (res.status === 201) {
            setSentEmail(true)
          }
        })
        .catch(() => {
          toast({
            description: 'Sending verification code failed!',
            className: 'text-red-500'
          })
        })
    } else {
      //TODO: toast already sent email, wanna re-send?
      toast({
        description: 'You have already sent an email',
        className: 'text-red-500'
      })
    }
  }

  const verifyCode = async (email: string, verificationCode: string) => {
    if (!emailVerified) {
      try {
        const response = await fetch(baseUrl + '/email-auth/verify-pin', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            pin: verificationCode,
            email: email
          })
        })
        if (response.status === 200) {
          setEmailVerified(true)
          setEmailAuthToken(response.headers.get('email-auth') || '')
        } else {
          // TODO: handle failure
          toast({
            description: 'Verification code is not valid!',
            className: 'text-red-500'
          })
        }
      } catch (error) {
        toast({
          description: 'Email verification failed!',
          className: 'text-red-500'
        })
      }
    } else {
      //TODO: email already verified
      toast({
        description: 'You have already verified code',
        className: 'text-red-500'
      })
    }
  }

  return (
    <div className="flex flex-col items-center justify-center">
      <Image src={CodedangLogo} alt="코드당" width={70} className="mb-5" />

      <form
        className="flex w-60 flex-col gap-4"
        onSubmit={handleSubmit(onSubmit)}
      >
        <Input
          placeholder="User Id"
          {...register('username')}
          error={errors.username?.message}
        />
        <div>
          <div className="flex gap-2">
            <Input
              id="email"
              type="email"
              placeholder="Email Address"
              {...register('email')}
              error={errors.email?.message}
            />
            <Button
              onClick={() => {
                const { email } = getValues()
                sendCodeToEmail(email)
              }}
              className="flex aspect-square w-12 items-center justify-center rounded-md bg-[#2279FD]"
            >
              <FaPaperPlane className="text-white" size="20" />
            </Button>
          </div>
          {sentEmail && (
            <p className="mt-1 text-xs text-blue-500">
              Email verification code has been sent!
            </p>
          )}
        </div>

        <div className="flex gap-1">
          <Input
            type="number"
            placeholder="Verification Code"
            {...register('verificationCode')}
            error={errors.verificationCode?.message}
          />
          <Button
            onClick={() => {
              const { email } = getValues()
              const { verificationCode } = getValues()
              verifyCode(email, verificationCode)
            }}
            className="flex aspect-square w-12 items-center justify-center rounded-md bg-[#2279FD]"
          >
            <FaCheck className="text-white" size="20" />
          </Button>
        </div>
        {emailVerified && (
          <p className="text-blue text-xs font-bold">
            Email has been verified!
          </p>
        )}
        <Input
          placeholder="Real Name"
          {...register('realName')}
          error={errors.realName?.message}
        />

        <div className="flex justify-between gap-2">
          <Input
            className="w-52"
            placeholder="Password"
            {...register('password')}
            type={passwordShow ? 'text' : 'password'}
            error={errors.password?.message}
          />
          <span className="mt-3" onClick={() => setPasswordShow(!passwordShow)}>
            {passwordShow ? <FaEyeSlash /> : <FaEye />}
          </span>
        </div>

        <div className="flex justify-between gap-2">
          <Input
            className="w-52"
            {...register('passwordAgain')}
            placeholder="Password Check"
            type={passwordAgainShow ? 'text' : 'password'}
            error={errors.passwordAgain?.message}
          />
          <span
            className="mt-3"
            onClick={() => setPasswordAgainShow(!passwordAgainShow)}
          >
            {passwordAgainShow ? <FaEyeSlash /> : <FaEye />}
          </span>
        </div>
        <Button color="blue" onClick={() => {}} type="submit">
          Register
        </Button>
      </form>
      <div className="text-gray-dark mt-6 flex flex-col items-center text-sm">
        Already have an account?
        <a className="text-gray-dark hover:text-gray-dark/80 active:text-gray-dark/60 w-fit cursor-pointer text-sm underline">
          Log In
        </a>
      </div>
      <Toaster />
    </div>
  )
}
