// frontend-client/app/(main)/_components/Footer.tsx
'use client'

import { IoIosLink } from 'react-icons/io'
import { RiGithubFill } from 'react-icons/ri'
import { RiKakaoTalkFill } from 'react-icons/ri'
import { TbMailFilled } from 'react-icons/tb'
import { toast } from 'sonner'

export default function Footer() {
  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText('skkucodingplatform@gmail.com')
      console.log('clipboard successfully set')
      toast.success('Email Copied!')
    } catch (err) {
      console.error('clipboard failed', err)
    }
  }
  return (
    <footer className="w-full items-center py-7">
      <div className="flex h-20 w-full flex-col items-center justify-center gap-2 bg-gray-100 text-slate-500">
        <div className="flex flex-row items-center justify-center gap-4">
          <a
            href="https://pf.kakao.com/_UKraK/chat"
            rel="noreferrer noopener"
            target="_blank"
          >
            <RiKakaoTalkFill
              className="cursor-pointer hover:text-slate-600"
              size="24"
            />
          </a>
          <TbMailFilled
            onClick={copyToClipboard}
            className="cursor-pointer hover:text-slate-600"
            size="24"
          />
          <a
            rel="noreferrer noopener"
            target="_blank"
            href="https://github.com/skkuding/"
          >
            <RiGithubFill
              className="cursor-pointer hover:text-slate-600"
              size="24"
            />
          </a>
          <a
            rel="noreferrer noopener"
            target="_blank"
            href="https://skkuding.dev/"
          >
            <IoIosLink
              className="cursor-pointer hover:text-slate-600"
              size="23"
            />
          </a>
        </div>
        <div>
          <p className="text-sm font-bold">
            (c) SKKUDING &nbsp;&nbsp;/ Since 2021
          </p>
        </div>
      </div>
    </footer>
  )
}

// frontend/client/src/common/components/Organism/Footer.vue
<script setup lang="ts">
import IconGithub from '~icons/fa6-brands/github'
import IconEnvelope from '~icons/fa6-solid/envelope'
import IconKakaoTalk from '~icons/ri/kakao-talk-fill'
import IconLink from '~icons/fa6-solid/link'
import { useClipboard } from '@vueuse/core'
import { useToast } from '@/client/src/common/composables/toast'

const { copy } = useClipboard()
const openToast = useToast()

const copyEmail = () => {
  copy('skkucodingplatform@gmail.com')
  openToast({ message: 'Email copied!', type: 'success' })
}
</script>

<template>
  <footer
    class="bg-gray-light text-gray-dark mt-auto flex w-full flex-col items-center gap-y-2 py-4"
  >
    <div
      class="[&>a:hover]:text-gray [&>a:active]:text-gray-light flex flex-row gap-x-4 text-xl [&>a]:cursor-pointer [&>a]:transition"
    >
      <a href="https://github.com/skkuding/skku-coding-platform">
        <IconGithub />
      </a>
      <a @click="copyEmail">
        <IconEnvelope />
      </a>
      <a href="http://pf.kakao.com/_UKraK/chat">
        <IconKakaoTalk />
      </a>
      <a href="https://npc.skku.edu">
        <IconLink />
      </a>
    </div>
    <div>© 2020-2022 SKKUDING</div>
  </footer>
</template>
