// frontend/src/common/components/Organism/Header.vue
<script setup lang="ts">
import Dropdown from '../Molecule/Dropdown.vue'
import SignatureLogo from '../Atom/SignatureLogo.vue'
import Fa6RegularUser from '~icons/fa6-regular/user'
const content = ['Management', 'Settings', 'Logout']
</script>
<template>
  <header
    class="border-b-gray sticky top-0 z-50 flex h-14 w-full min-w-[540px] content-center items-center justify-between border-b bg-white px-12 py-4 font-medium opacity-95"
  >
    <router-link to="/">
      <SignatureLogo class="hidden h-12 md:block" />
    </router-link>
    <nav>
      <router-link
        class="text-text-title hover:text-green mr-4 text-2xl font-medium hover:cursor-pointer hover:no-underline"
        active-class="text-green"
        to="/announcement"
      >
        Notice
      </router-link>
      <router-link
        class="text-text-title hover:text-green mr-4 text-2xl font-medium hover:cursor-pointer hover:no-underline"
        active-class="text-green"
        to="/contest"
      >
        Contest
      </router-link>
      <router-link
        class="text-text-title hover:text-green mr-4 text-2xl font-medium hover:cursor-pointer hover:no-underline"
        active-class="text-green"
        to="/problem"
      >
        Problem
      </router-link>
      <router-link
        class="text-text-title hover:text-green mr-8 text-2xl font-medium hover:cursor-pointer hover:no-underline"
        active-class="text-green"
        to="/group"
      >
        Group
      </router-link>
    </nav>
    <Dropdown :content="content">
      <template #dropdown-icon>
        <Fa6RegularUser class="text-text-title hover:text-green" />
      </template>
    </Dropdown>
  </header>
</template>

// frontend-client/components/Header.tsx
import ButtonWithModal from '@/components/ButtonWithModal'
import Signin from '@/components/Signin'
import CodedangLogo from '@/public/codedang.svg'
import Image from 'next/image'
import Link from 'next/link'
import SignInUpButton from './SignInUpButton'

const Header = () => {
  return (
    <header className="border-b-gray grid h-16 place-items-center border-b bg-white px-5">
      <div className="flex w-full max-w-7xl items-center justify-between gap-5">
        <div className="flex w-1/2 min-w-fit items-center justify-between gap-8">
          <Link href="/">
            <Image src={CodedangLogo} alt="코드당" width={90} />
          </Link>
          <nav className="hidden gap-8 capitalize md:flex">
            <Link href="/notice" className="text-lg hover:opacity-60">
              Notice
            </Link>
            <Link href="/contest" className="text-lg hover:opacity-60">
              Contest
            </Link>
            <Link href="/problem" className="text-lg hover:opacity-60">
              problem
            </Link>
            <Link href="/group" className="text-lg hover:opacity-60">
              Group
            </Link>
          </nav>
        </div>
        <SignInUpButton />
      </div>
    </header>
  )
}

export default Header
