// frontend/src/problem/components/Header.vue
<script setup lang="ts">
import Dropdown from '@/common/components/Molecule/Dropdown.vue'
import SymbolLogo from '@/common/components/Atom/SymbolLogo.vue'
import IconUser from '~icons/fa6-regular/user'
import { ref } from 'vue'
import ListItem from '@/common/components/Atom/ListItem.vue'
import AuthModal from '@/common/components/Organism/AuthModal.vue'
import Button from '@/common/components/Atom/Button.vue'
import Fa6SolidAngleRight from '~icons/fa6-solid/angle-right'

const auth = ref(true)
const modalContent = ref<'login' | 'signup' | 'password' | 'close'>('close')
</script>

<template>
  <header
    class="border-b-gray bg-text-subtitle grid h-14 place-items-center border-b px-8"
  >
    <div class="flex h-14 w-full max-w-7xl items-center justify-between">
      <div class="flex h-14 items-center">
        <RouterLink class="mr-4" to="/">
          <SymbolLogo
            class="h-10 fill-white transition-opacity hover:opacity-80 active:opacity-60"
          />
        </RouterLink>
        <RouterLink
          class="hidden text-lg font-bold text-white/60 transition-colors hover:text-white active:text-white/80 md:inline"
          to="/contest"
        >
          Contents
        </RouterLink>
        <Fa6SolidAngleRight class="mx-2 hidden text-white/60 md:inline" />
        <RouterLink
          class="hidden text-lg font-bold text-white/60 transition-colors hover:text-white active:text-white/80 md:inline"
          to="/contest/1"
        >
          SKKU 코딩 플랫폼 대회
        </RouterLink>
        <Fa6SolidAngleRight class="mx-2 hidden text-white/60 md:inline" />
        <span class="text-lg font-semibold text-white">가파른 경사</span>
      </div>
      <Transition
        enter-active-class="transition-opacity duration-300"
        leave-active-class="transition-opacity duration-300"
        enter-from-class="opacity-0"
        leave-to-class="opacity-0"
        mode="out-in"
      >
        <div v-if="auth">
          <Dropdown class="bg-slate-500 text-white">
            <template #button>
              <IconUser class="text-xl text-white" />
            </template>
            <template #items>
              <!-- TODO: change text color after PR #316 -->
              <ListItem>Management</ListItem>
              <ListItem>My Page</ListItem>
              <ListItem @click="auth = false">Log Out</ListItem>
            </template>
          </Dropdown>
        </div>
        <div v-else class="inline-flex gap-2">
          <Button color="white" outline @click="modalContent = 'signup'">
            Sign Up
          </Button>
          <Button color="white" outline @click="modalContent = 'login'">
            Log In
          </Button>
        </div>
      </Transition>
    </div>
  </header>
  <AuthModal v-model="modalContent" />
</template>

// frontend-client/components/Header.tsx
import ButtonWithModal from '@/components/ButtonWithModal'
import Signin from '@/components/Signin'
import CodedangLogo from '@/public/codedang.svg'
import Image from 'next/image'
import Link from 'next/link'

const Header = () => {
  return (
    <header className="border-b-gray grid h-16 place-items-center border-b bg-white px-5">
      <div className="flex w-full max-w-7xl items-center justify-between gap-5">
        <div className="flex w-1/2 min-w-fit items-center justify-between gap-8">
          <Link href="/">
            <Image src={CodedangLogo} alt="코드당" width={90} />
          </Link>
          <nav className="hidden gap-8 capitalize md:flex">
            <Link href="/notice" className="text-lg hover:opacity-60">
              Notice
            </Link>
            <Link href="/contest" className="text-lg hover:opacity-60">
              Contest
            </Link>
            <Link href="/problem" className="text-lg hover:opacity-60">
              problem
            </Link>
            <Link href="/group" className="text-lg hover:opacity-60">
              Group
            </Link>
          </nav>
        </div>
        <div className="ml-2 hidden items-center gap-2 md:flex">
          <ButtonWithModal
            buttonText="Sign in"
            buttonVariant={'outline'}
            className="border-none font-semibold"
          >
            <Signin />
          </ButtonWithModal>
          <ButtonWithModal
            buttonText="Sign up"
            buttonVariant={'outline'}
            className="font-bold"
          >
            <Signin />
          </ButtonWithModal>
        </div>
      </div>
    </header>
  )
}

export default Header
