// frontend/src/common/components/Molecule/Modal.vue
<script setup lang="ts">
import { computed } from 'vue'
import IconoirCancel from '~icons/iconoir/cancel'

const props = defineProps<{
  title: string
  titleColor?: string
}>()
defineEmits(['close'])

const ModalStyle = computed(() => {
  return props.titleColor === 'green' ? 'text-green' : 'text-gray'
})
</script>

<template>
  <div class="ml-auto mr-auto">
    <div class="fixed top-0 left-0 h-screen w-screen bg-black opacity-25"></div>

    <div
      class="relative z-50 h-full w-full rounded-lg bg-white p-2 text-center"
    >
      <IconoirCancel
        class="text-gray absolute right-0 cursor-pointer"
        @click="$emit('close')"
      />
    </div>
    <span :class="ModalStyle">{{ title }}</span>
    <div>
      <slot name="modal-content">default content</slot>
    </div>
  </div>
</template>

// frontend-client/components/Modal.tsx
'use client'

import { RxCross2 } from 'react-icons/rx'

interface ModalProps {
  children: React.ReactNode
  isOpen: boolean
  close: () => void
}

const Modal = ({ children, isOpen, close }: ModalProps) => {
  return (
    <>
      {isOpen && (
        <div
          className="fixed bottom-0 left-0 right-0 top-0 z-50 flex items-center justify-center bg-black/10 p-5 backdrop-blur-md"
          onClick={close}
        >
          <div
            className="relative rounded-lg bg-white p-7 pb-10"
            onClick={(e) => {
              e.stopPropagation()
            }}
          >
            <button onClick={close} className="absolute right-3 top-3">
              <RxCross2 className="text-lg opacity-30 hover:opacity-80" />
            </button>
            {children}
          </div>
        </div>
      )}
    </>
  )
}

export default Modal
